spring:
  application:
    name: event-management
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: false
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

microsoft:
  client-id: ${MICROSOFT_CLIENT_ID}
  client-secret: ${MICROSOFT_CLIENT_SECRET}
  tenant-id: ${MICROSOFT_TENANT_ID}
  scopes: 
    - https://graph.microsoft.com/.default